export { default as whiteArrow } from '/src/assets/icons/white-arrow-bottom.svg"'
export { default as closeIcon } from '/src/assets/icons/close.svg'
export { default as reactIcon } from '/src/assets/icons/react.svg'
export { default as figmaIcon } from '/src/assets/icons/figma.svg'
export { default as whiteVector } from "../../assets/icons2/personal-info.svg"
export { default as grayVector } from '../../assets/icons2/gray-vector.svg'
export { default as greenFolder } from '../../assets/icons2/green-folder.svg'
export { default as redFolder } from '../../assets/icons2/red-folder.svg'
export { default as blueFolder }from  '../../assets/icons2/blue-folder.svg'
export { default as htmlIcon } from '../../assets/icons2/html-icon.svg'
export { default as cssIcon } from '../../assets/icons2/css-icon.svg'
export { default as jsIcon } from '../../assets/icons2/javascript-icon.svg'
export { default as reactIcon } from  '../../assets/icons2/react-js-icon.svg'
export { default as sassIcon } from '../../assets/icons2/sass-icon.svg'
export { default as tsIcon }  from '../../assets/icons2/typescript-icon.svg'
export { default as gitIcon } from  '../../assets/icons2/git-icon.svg'
export { default as mailIcon } from '../../assets/icons2/mail-icon.svg'
export { default as phoneIcon } from '../../assets/icons2/phone-icon.svg'